### ISSUE TITLE
Entry points

### ISSUE THREAD

**Issue by agrimaldi** [LTLA/diffHic#4]
Hi there,

I was wondering if there are other entry points for input data besides the fastq files.
I am currently using another pipeline to process the data, so I already have binned, filtered and corrected Hic matrices at various resolutions. I could export those to some flat file format (either sparse matrix notation or full matrix).
What would be needed to load such files into a `data` object (as described in the documentation) ?

**Comment by LTLA** [comment]
The best way would be to use the `iset` branch (which, hopefully, will become the `master` soon). It uses methods in the _InteractionSet_ package which supports interaction matrices. The idea would be to load your data into a `ContactMatrix` using standard methods, e.g., by loading it in as a (sparse) matrix and then constructing a `ContactMatrix`. You can then `deflate` this to form an `InteractionSet` object - if you repeat for each library, you can then `cbind` everything together to get something like `data`.

This might require some work to ensure that the same interactions are generated for each library, otherwise the `cbind`ing won't work properly. I also should stress that _diffHic_ depends on raw count data, so you should really pick the appropriate matrix to use here. Something holding raw binned counts would be ideal.

**Comment by agrimaldi** [comment]
Thanks! (I guess this is gonna make me a masochist)
I'll try that and will let you know if run into issues

**Comment by LTLA** [comment]
I just modified the `deflate` method to take an `extract` argument, which should allow standardized extraction of interactions across multiple `ContactMatrix` objects. The idea is to do something like this:

```
# Select interesting interactions; in this case, non-zero in at least one library
to.keep <- as.matrix(cm1)!=0 | as.matrix(cm2)!=0 
iset1 <- deflate(cm1, extract=to.keep)
iset2 <- deflate(cm2, extract=to.keep)
data <- cbind(iset1, iset2)
```

... which is a lot easier than trying to wrangle the `InteractionSet` objects into shape.

**Comment by agrimaldi** [comment]
So, I got kinda stuck trying to install diffHic from source.
I ran into the following problems:
- The required R version is >= 3.3.0, but as far as I know, the latest one is 3.2.3
- I tried installing SummarizedExperiment from bioconductor (I understand it is required), but for some reason got an error message telling me that this package does not exist for the version of R I'm using (3.2.1) while the requirement state R (>= 3.2).

I'm not an R person, and I realize these errors are out of the scope of diffHic per-se, but if you have any hints as to how to properly install it from source, that would be awesome.

**Comment by LTLA** [comment]
The development version of _diffHic_ runs off Bioconductor 3.3, which in turn runs off R-devel (i.e., version 3.3.0). So, you'll need to start by installing R-devel, and then installing packages in Bioc-devel. If you can do the former, you can easily do the latter by following the standard BioC installation procedure.

**Comment by agrimaldi** [comment]
Jesus, installing all the required package is not the easiest thing.

Did you have any trouble installing rhdf5 in R-devel ?
I get a lot of conflicts between function declarations in cmath:
```
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cmath:464: error: declaration of C function ‘long double std::tanh(long double)’ conflicts with
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cmath:460: error: previous declaration ‘float std::tanh(float)’ here
```

**Comment by LTLA** [comment]
Hmm, I haven't had any problems on my end. That seems like a pretty strange problem; do other C++ programs using `cmath` build properly on your system? Or, does _rhdf5_ install properly in release R?

**Comment by agrimaldi** [comment]
Yes, it builds fine using R 3.2.3. May I know which R-devel version you are using ?
Thanks for your help

**Comment by LTLA** [comment]
```
R Under development (unstable) (2015-12-22 r69809)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
```

Are you building your R installation from source? I've had some troubles on RHEL in the past.

**Comment by agrimaldi** [comment]
Awesome, that did it!
I'll let you know if run into troubles using diffHic itself

**Comment by agrimaldi** [comment]
Alright, I've been playing with some basic stuff, essentially loading the whole Hic maps unto ContactMatrix objects, basic filtering, dispersion estimation and significant interactions calling. So far so good.

In the documentation, there is a section about restricting the dataset to a subset of genomic regions (genes for example).
The following code is used:
```R
> require(TxDb.Mmusculus.UCSC.mm10.knownGene)
> gene.body <- genes(TxDb.Mmusculus.UCSC.mm10.knownGene)
> redata <- connectCounts(input, mm.param, regions=gene.body)
> redata
```

Now, the problem with connectCount, is that the files with the mapped reads are required (I assume to load only those reads that fall in the requested genomic features)
Is there any way to directly apply the filtering of those regions of interest when building the contact matrix ?

Also, when I create my data object as you suggested it, I have the following:
```R
> data
class: InteractionSet
dim: 2855439 8
metadata(0):
assays(1): ''
rownames: NULL
rowData names(0):
colnames(8): 1 11 ... 16 17
colData names(0):
type: StrictGInteractions
regions: 2754
```

However, when trying to do operations on the diagonal (filtering or normalizing separately from the rest of the contact matrix):
```R
> filterDiag(data)
Error in .check_StrictGI(data) :
  'interactions' slot of InteractionSet must be a 'ReverseStrictGInteractions'
```

Any ideas ?
Thanks

**Comment by LTLA** [comment]
You've got bin pairs, so you can't reload counts for gene pairs unless you have the raw data. However, you can restrict the analysis to gene pairs by identifying the bin pairs that overlap pairs of genes. Check out `linkOverlaps`, which will tell you which bin pairs link together two genes. You can also use `findOverlaps` and the like to identify bin pairs with anchor regions overlapping one or more genes.

For your second problem, it should be easily fixed with:

```
interactions(data) <- as(interactions(data), "ReverseStrictGInteractions")
```

This isn't the default because I've never anticipated this usage pattern for _diffHic_.
